#!/usr/bin/env bash

#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local url_consul_template_Darwin="https://releases.hashicorp.com/consul-template/${CONSUL_TEMPLATE_VERSION}/consul-template_${CONSUL_TEMPLATE_VERSION}_darwin_amd64.zip"
  local url_consul_template_Linux="https://releases.hashicorp.com/consul-template/${CONSUL_TEMPLATE_VERSION}/consul-template_${CONSUL_TEMPLATE_VERSION}_linux_amd64.zip"

  local url_consul_template="url_consul_template_$(uname -s)"
  local fnm_consul_template="$(basename "${!url_consul_template}")"

  cache curl "$fnm_consul_template" "${!url_consul_template}"
  
  pushd bin
  unzip -o "${CACHE_DIR}/curl/$fnm_consul_template"
  chmod 755 consul-template
  popd

  local url_confd_template_Darwin="https://github.com/kelseyhightower/confd/releases/download/v${CONFD_VERSION}/confd-${CONFD_VERSION}-darwin-amd64"
  local url_confd_template_Linux="https://github.com/kelseyhightower/confd/releases/download/v${CONFD_VERSION}/confd-${CONFD_VERSION}-linux-amd64"

  local url_confd_template="url_confd_template_$(uname -s)"
  local fnm_confd_template="$(basename "${!url_confd_template}")"

  cache curl "$fnm_confd_template" "${!url_confd_template}"
  
  rsync -ia "${CACHE_DIR}/curl/$fnm_confd_template" "$shome/bin/confd"
  chmod 755 "$shome/bin/confd"
}

bootstrap
