#!/usr/bin/env bash

function _consul_agent_profile {
  local shome="${_consul_agent_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"

  CONSUL_TEMPLATE_VERSION='0.19.0'
}

_consul_agent_profile
