#!/usr/bin/env bash

function _consul_home_profile {
  local shome="${_consul_home_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$PATH"

  CONSUL_TEMPLATE_VERSION='0.18.0'
}

_consul_home_profile
