#!/usr/bin/env bash

function consul_server {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$#" == 0 ]]; then
    set -- default
  fi

  case "${1:-}" in
    default)
      exec 2>&1
      set -x

      while ! ping -c 1 -t 3 consul.service.consul; do
        sleep 1
      done
      
      while [[ ! -f "$shome/etc/consul.json" ]]; do
        sleep 1
      done

      local ip_client="$(runmany 'ifconfig $1 2>/dev/null || true' eth0 enp0s8 | grep 'inet addr' | awk '{print $2}' | cut -d: -f2)"
      exec consul agent -config-dir="$shome/etc" -join consul.service.consul -advertise "$ip_client"
      ;;
    *)
      echo "ERROR: unknown server command: ${1:-/not-supplied/}" 1>&2
      return 1
      ;;
  esac
}

consul_server "$@"
